project_id = "wnajjqsqmrpwyffbpgsj"

[functions.accept-ride]
verify_jwt = true

[functions.moderate-content]
verify_jwt = true

[functions.send-verification-notification]
verify_jwt = true

[functions.send-support-notification]
verify_jwt = true

[functions.send-offer-notification]
verify_jwt = true

[functions.send-ride-accepted-notification]
verify_jwt = true

[functions.send-cancellation-notification]
verify_jwt = true

[functions.send-rating-notification]
verify_jwt = true

[functions.send-status-notification]
verify_jwt = true
